### ISSUE TITLE
Is there a way to sample the databricks logs before sending to log analytics workspace?

### ISSUE THREAD

**Issue by ZhouDavid** [mspnp/spark-monitoring#100]
Recently found the volume of logs flushing into the log analytics workspace is amazingly large. While usually only some specific levels of logs are necessary, is there a way to do some filtering before sending?

**Comment by al-lac** [comment]
We have the same issue. Would be great if someone could provide a solution for this.

**Comment by hallihan** [comment]
I did some quick experiments with filtering the data, see info and samples in this branch: <https://github.com/mspnp/spark-monitoring/blob/experiment-filtering/FILTER.md>

**Comment by hallihan** [comment]
I'm going to close this issue as duplicate, follow #95 for updates on this topic.
