### ISSUE TITLE
spark-listeners_2.4.5_2.11:jar:1.0.0 unavailability

### ISSUE THREAD

**Issue by agneslydia92** [mspnp/spark-monitoring#102]
Am getting this error:
_The POM for com.microsoft.pnp:spark-listeners_2.4.5_2.11:jar:1.0.0 is missing, no dependency information available_ while building jar for spark-listeners-loganalytics.

**Comment by hallihan** [comment]
I believe the comment from Aug 21 will help get this build working for you.  Feel free to reopen with additional details if you are still having trouble.
