### ISSUE TITLE
Improve quality of the information

### ISSUE THREAD

**Issue by justPaulo** [mspnp/spark-monitoring#105]
In section "Viewing the Sample Job's Logs in Log Analytics"
Update types to:
SparkListenerEvent_CL
SparkLoggingEvent_CL
**SparkMetric_CL**

Where is "spark-jobs" mentioned also in the README.md file ?

**Comment by hallihan** [comment]
The sample job is now under ```sample/spark-sample-job/```.  Thanks for the feedback on the other items, you are welcome to submit a pull request to update the README.md, or I will include the changes in updates later this quarter.
