### ISSUE TITLE
Bash shell script in "Create Dashboard" section doesn't work as expected

### ISSUE THREAD

**Issue by ckittel** [mspnp/spark-monitoring#108]
Moved over from MicrosoftDocs/architecture-center#2368 by @justPaulo

> [Output is: sed: 1: "/workspace/c\ \t\t\t" ...": extra characters after \ at the end of c command]
> 
> Content: [Use dashboards to visualize Azure Databricks metrics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/dashboards)
> Content Source: [docs/databricks-monitoring/dashboards.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/dashboards.md)

Seems like the solution will be here, instead of on the docs.  Please correct me if I'm wrong.

**Comment by justPaulo** [comment]
I see no difference, tried it again and got same error result as before. The contend of the MD file is the same as the docs.

**Comment by ckittel** [comment]
Sorry if this caused confusion, @justPaulo.  I just copied the GitHub issue from one repo to another; we didn't address your concern yet.  The fix, when it is complete, will happen here in this "spark-monitoring" repo -- not in the documentation repo where the issue was first opened.  I moved it here for added engineering visibility and prioritization on our backlog.

**Comment by justPaulo** [comment]
No worries, thank you for clarifying.

**Comment by hallihan** [comment]
@justPaulo The error you are seeing will occur if you are using the stock `sed` command on MacOS, or another POSIX `sed` implementation.  The script is expecting GNU's sed implementation.  You can install the GNU version of sed from [Homebrew](https://formulae.brew.sh/formula/gnu-sed) with `brew install gnu-sed` and then alter the commands to use `gsed`, or alter your path so that the GNU version is found first.

**Comment by justPaulo** [comment]
Didn't see that coming... you're the man @hallihan 
Worked like a breeze, thanks much. Maybe it wouldn't be a bad idea to put your comment about gsed x sed into the documentation.
