### ISSUE TITLE
Latest build only supports 2.4.3 and 2.4.5

### ISSUE THREAD

**Issue by chase-edwards-db** [mspnp/spark-monitoring#109]
The latest build (b8193707e849e661473f8cae71e60078f503e931) only allows these two versions to be compiled. This is a regression from previous versions. Looking for clarity on why this decision was made. These two versions are the only two included in "build.sh".

**Comment by hallihan** [comment]
We did this to align with the currently supported Azure Databricks 5.x and 6.x releases at: <https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/releases>. (should be aligned with <https://docs.databricks.com/release-notes/runtime/releases.html#supported-releases>) The change was made in #106.   What version(s) are you looking to have included?

**Comment by Emresav** [comment]
Do you plan to extend this to support Azure Databricks 7.x and Spark3.0.x? @hallihan Thanks

**Comment by hallihan** [comment]
@Emresav we have work planned later this quarter, I'm afraid I can't provide an ETA at this point. Follow #92 for updates.  Closing this issue since removing unsupported versions was intentional.
