### ISSUE TITLE
Dependency error while trying to build sample jars

### ISSUE THREAD

**Issue by hurtn** [mspnp/spark-monitoring#111]
[ERROR] Failed to execute goal on project spark-monitoring-sample: Could not resolve dependencies for project com.microsoft.pnp:spark-monitoring-sample:jar:1.0.0: Could not find artifact com.microsoft.pnp:spark-listeners_2.4.5_2.11:jar:1.0.0 in central (https://repo.maven.apache.org/maven2)

**Comment by hallihan** [comment]
The error above looks like you were trying to build directly in one of the subdirectories.  Are you using the build instructions from: <https://github.com/mspnp/spark-monitoring#build-the-azure-databricks-monitoring-library>?  The docker build is the easiest.  If you are building with Maven, you need to make sure your environment is set up for Java 8, change to the  `spark-monitoring/src` directory, and run a command like `mvn -P "scala-2.11_spark-2.4.5" package` to specify a profile for the build.  If this doesn't help, please reopen the issue with additional details.

**Comment by hurtn** [comment]
Thank you. Wasn't quite so straight forward, got it working in the end by copying the logging jars into the repository path (.m2) for the sample build
