### ISSUE TITLE
Log Analytics Query Examples

### ISSUE THREAD

**Issue by locuba** [mspnp/spark-monitoring#113]
Hello,

I've installed the library as explained in your documentation and it's collecting data to the Log Analytics table SparkMetric_CL however i'm struggling since a month to get relevant & precise query.

As instance, I want to follow my Driver memory consumption (which max size is 56GB). That looks easy so I've created the query:
```
SparkMetric_CL
| where name_s contains "driver.jvm.total."
| where executorId_s == "driver"
| extend memUsed_GB = value_d / 1000000000
| project TimeGenerated, name_s, memUsed_GB
| summarize avg(memUsed_GB) by tostring(name_s), bin(TimeGenerated, 1h) 
```
![image](https://user-images.githubusercontent.com/69255516/95070608-a8ea6b00-0708-11eb-9e47-fa6e6a41754b.png)
As per the query only 4GB of 42GB is used (I don't even know why 56GB is not the max). Then I'm checking the memory consumption of the VM hosting my databricks Driver where consumption is 50%. I understand that my query on SparkMetric_CL table is probably wrong:
![image](https://user-images.githubusercontent.com/69255516/95070662-bbfd3b00-0708-11eb-8611-125d7ae6fd89.png)

**Do you have pre-made Log Analytics queries that could help to set up monitoring dashboards?** The Spark metrics are not easy to understand, even after reading their [documentation](https://spark.apache.org/docs/latest/monitoring.html). My query is probably wrong I'm really lost with the way to use those metrics and to be sure the values are correct and I don't misunderstand them..

Having a section in your documentation with some examples would be helpful (like how to get memory/cpu consumption of driver or workers...)

**Comment by hallihan** [comment]
@locuba I'm curious what your chart would look like if you chart max instead of avg, and use a smaller time bin, like:
 ```| summarize max(memUsed_GB) by tostring(name_s), bin(TimeGenerated, 1m)```

**Comment by locuba** [comment]
@hallihan here what I have with the suggested query for the last 48 hours:
```
SparkMetric_CL
| where name_s contains "driver.jvm.total."
| where executorId_s == "driver"
| extend memUsed_GB = value_d / 1000000000
| project TimeGenerated, name_s, memUsed_GB
| summarize max(memUsed_GB) by tostring(name_s), bin(TimeGenerated, 1m)
```
![image](https://user-images.githubusercontent.com/69255516/95167863-ac393180-07b0-11eb-8aa8-5a74ddb2db5f.png)
So the memory consumption looks to increase up to 10GB then decrease (most probably because of GAC operation releasing it). I'm not really sure that my Driver memory is really used at less than 10GB since the VM hosting and acting as Driver is consuming 50% of available memory (near 28GB of 56GB, from Azure Monitor metrics)
