### ISSUE TITLE
test cases are failing as it is unable to find org.apache.spark.SparkInformation

### ISSUE THREAD

**Issue by shravan-sambaraju** [mspnp/spark-monitoring#120]
Hi i am trying to build the jar following the steps as suggested for maven but getting test case failures and when I dig deeper I found that it is unable to locate org.apache.spark.SparkInformation;

I tried to change my jdk and issue still persists.

**Comment by hallihan** [comment]
@shravan-sambaraju what versions of Maven and JDK are you using?

**Comment by hallihan** [comment]
We have made some changes to the build instructions to try and make things easier.  Please check out https://github.com/mspnp/spark-monitoring#prerequisites for the specific versions of Maven and JDK, and https://github.com/mspnp/spark-monitoring#build-the-azure-databricks-monitoring-library for build instructions.  If you are still hitting an error, feel free to re-open this issue with more details.
