### ISSUE TITLE
Unable to build the project for Jar creation

### ISSUE THREAD

**Issue by yuraje** [mspnp/spark-monitoring#122]
Hello,

I followed the guidelines to create the jar for Spark monitoring in Log Analytics. with the recent update on version and Spark 3.0 profile I couldn't able to build the project for creating the jar. 

Can someone please point me if I'm missing anything. 

**Error:**
java: cannot find symbol
symbol:   class SparkInformation
location: package org.apache.spark

**Comment by hallihan** [comment]
Can you provide the specific command you are running when you get this error?  The Docker build instructions are usually the easiest (if you have Docker) since they handle setting up the build container with the expected versions. (https://github.com/mspnp/spark-monitoring#option-1-docker)

**Comment by yuraje** [comment]
Thank you @hallihan for your response. 
I m using IntelliJ IDEA development environment to build the given got project by referring the instruction given in the git. 
The error which I encounter while building the project is... 

java: cannot find symbol
symbol: class SparkInformation
location: package org.apache.spark

Will you be able to help me out here on what went wrong with this environment.

**Comment by hallihan** [comment]
Can you try manually unchecking and re-checking the profile in the Maven tab and then try to rebuild:
<img width="601" alt="Screen Shot 2021-01-25 at 1 21 00 PM" src="https://user-images.githubusercontent.com/1796255/105748729-862acf00-5f10-11eb-91c6-2baab66c02c7.png">
If that doesn't work, try a fresh clone of the repository.  There are a lot of IntelliJ files that are included in .gitignore that may be holding on to some old settings.

**Comment by yuraje** [comment]
Hi @hallihan, When we retried with the fresh clone and with JDK1.8 it work! 
Now We created the JAR file as per the document. Fantastic & Thank you!

But the real problem here is after adding the JAR and .sh file to Init Script, when we restarted the ADB cluster it didnt started.
It terminated and when we removed the .sh file from Init Script then the cluster is starting without any issue.

Can you please help out here. 

P.S: We tried with Cluster runtime (7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)) and also with (6.4 (includes Apache Spark 2.4.5, Scala 2.11) - JAR created with Scala2.11_Spark2.4.5 profile) None of it helped.


![image](https://user-images.githubusercontent.com/57178002/106611557-2080b780-658e-11eb-83fc-b36bafde4855.png)

**Comment by hallihan** [comment]
This behavior usually indicates a problem with the configuration of the Log Analytics workspace.  Can you check step 2 of https://github.com/mspnp/spark-monitoring/#configure-the-databricks-workspace and confirm that these changes were made before you uploaded the spark-monitoring.sh script?

**Comment by yuraje** [comment]
@hallihan, Yeah I've added the WorkSpaceId and the Key in the .sh file before I place it in dbfs location. 
The same was referred in the Init Script.

![image](https://user-images.githubusercontent.com/57178002/106629494-e836a480-65a0-11eb-8a93-cba312a7e454.png)

**Comment by hallihan** [comment]
If you turn on cluster logging then you can retrieve the logs from the init script from dbfs.

Edit the cluster to enable logging to dbfs:
![image](https://user-images.githubusercontent.com/1796255/106636024-7e41df00-654f-11eb-9a6f-0cb4ad8ae524.png)

Then you can find the logs in dbfs:
`dbfs ls dbfs:/cluster-logs` - keep adding to the path until you find the specific logs, example:
`dbfs ls dbfs:/cluster-logs/<clusterid>/init_scripts/<startid>`

Then you can cat the stdout and stderr files to see what error is occuring:
`dbfs cat dbfs:/cluster-logs/<clusterid>/init_scripts/<startid>/<timestamp>_spark-monitoring.sh.stderr.log`

**Comment by yuraje** [comment]
@hallihan, After enabling the log I was able to trace the issue and fix it. When I upload the Jar and .sh file the certain special characters are changing in the file name and it created issue. I have corrected this and able to push the log to LogAnalytics work space. I appreciate your help! thank you..
