### ISSUE TITLE
Not able to access Spark Logging table in Log Analytics workspace

### ISSUE THREAD

**Issue by saumyabahuk** [mspnp/spark-monitoring#132]
Only 2 custom tables ie spark metric and spark listener event are created when built jar is deployed on the cluster. The third table which sends cluster logs is not getting created. Is there some issue with the way jar is built or with the code?

**Comment by hallihan** [comment]
Did you configure your job similar to the sample job, specifically with the additional appender definition like in https://github.com/mspnp/spark-monitoring/blob/master/sample/spark-sample-job/src/main/resources/com/microsoft/pnp/samplejob/log4j.properties ?

**Comment by hallihan** [comment]
Please feel free to re-open if you have additional details for troubleshooting
