### ISSUE TITLE
Support for Databricks Runtime 8.x

### ISSUE THREAD

**Issue by hungnguyen10897** [mspnp/spark-monitoring#133]
Databricks has introduced new runtime version 8.x with Scala 2.12 and Spark 3.1.1. 

It would be nice to have corresponding version of the library.

**Comment by al-lac** [comment]
Would be really great to have this quickly!

**Comment by AnouarSeg** [comment]
Indeed, it would awesome to support this new runtime version.

**Comment by hallihan** [comment]
I have done some initial testing and there are a handful of breaking changes to resolve, so this will take a little bit longer to support.

**Comment by Joon** [comment]
Bumping this as Spark on Synapse has also announced support for Spark V3 runtimes.

**Comment by jvalley19** [comment]
Hi do we have an ETA on when this functionality to support Runtime 8.x will be available?

**Comment by sheigel** [comment]
I guess the only thing left is to accept defeat and delete the documentation page https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs . At least not confuse people with recommendations that don't work.

**Comment by planetjones** [comment]
Microsoft describe this solution on their website at https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs .  By doing that it implies that this is more than a homebrew solution that is used at your own risk in case of DB version upgrades, which we have had to take so the service principal auth between Databricks and Synapse or the dedicated SQL pool works with the Databricks connector.  I guess we can raise a support ticket at Microsoft so they can at least qualify their documentation to say this might break when the DB version breaks.

**Comment by hallihan** [comment]
I have some time scheduled to try and address this next sprint (June 21 - July 2), but can't guarantee when I'll be able to complete it.  If anyone is working on this independently, I'm happy to review pull requests in accordance with [CONTRIBUTING.md](https://github.com/mspnp/spark-monitoring/blob/master/CONTRIBUTING.md) and the [LICENSE](https://github.com/mspnp/spark-monitoring/blob/master/LICENSE).
