### ISSUE TITLE
StreamingQueryListenerSampleJob: command not found when initializing the cluster

### ISSUE THREAD

**Issue by Borfnog** [mspnp/spark-monitoring#136]
Hello,  i'm wondering if anybody can please help with my issue with this package in that my cluster is failing to load and the stderr log reports the following :

**bash: line 18: StreamingQueryListenerSampleJob: command not found
bash: line 18: FS_CONF_COMPAT: command not found**

I have made no changes to the script except changing the JAR filenames.

On a separate note, i'm a non-java developer trying to muddle my way through getting these JARs built in order to move forward. Is there any plan to provide these as ready built packages it would help so much.

Many thanks in advance for any advice.
Kind regards,
Nick

**Comment by sayanmanik** [comment]
Also facing the same issue

**Comment by hallihan** [comment]
This is an odd error.  Those strings are only included in comments in the startup script: https://github.com/mspnp/spark-monitoring/blob/master/src/spark-listeners/scripts/spark-monitoring.sh#L46 - Are you attempting to use [filtering](https://github.com/mspnp/spark-monitoring/blob/master/docs/filtering.md)?

**Comment by hallihan** [comment]
Closing since no additional information was provided.  Feel free to reopen with more details if help is still needed.
