### ISSUE TITLE
How to make this work for Azure China?

### ISSUE THREAD

**Issue by jurejoy** [mspnp/spark-monitoring#141]
It's great project working for global azure. But looks like the endpoint and authentication only works for global Azure, anyone can point that where to modify in the code side to make this work for Azure China?

**Comment by TheoDoreW** [comment]
Set ”private static final String DEFAULT_URL_SUFFIX = "ods.opinsights.azure.com";“ to "private static final String DEFAULT_URL_SUFFIX = "ods.opinsights.azure.cn";", and then it works.

**Comment by jurejoy** [comment]
> Set ”private static final String DEFAULT_URL_SUFFIX = "ods.opinsights.azure.com";“ to "private static final String DEFAULT_URL_SUFFIX = "ods.opinsights.azure.cn";", and then it works.

Great

> Set ”private static final String DEFAULT_URL_SUFFIX = "ods.opinsights.azure.com";“ to "private static final String DEFAULT_URL_SUFFIX = "ods.opinsights.azure.cn";", and then it works.

Great, it works! Thanks and will close this issue.
