### ISSUE TITLE
Commands are not getting executed in Azure Databricks.

### ISSUE THREAD

**Issue by mandar-degvekar** [mspnp/spark-monitoring#145]
Hello Team,

I have configured everything, created jars using MAVEN, given appropriate information in shell file and added it as a part of init script while spinning off the cluster. 

Jobs are getting cancelled automatically and there is nothing in spark event tab for the cluster. 

I'm getting below mentioned error when I try to run any command on Databricks in Spark UI.

![image](https://user-images.githubusercontent.com/51981421/126489452-5fb770c6-a1af-4bf1-81a1-ec70ab1b6374.png)

**Comment by mandar-degvekar** [comment]
I'm adding screenshot for log file : 

![image](https://user-images.githubusercontent.com/51981421/126590750-0f5aabc0-990e-4962-8896-96bfbb8f07dc.png)

**Comment by mandar-degvekar** [comment]
@hallihan can you please help me with this issue ?

**Comment by hallihan** [comment]
Are you still seeing this issue?  If so, please provide additional details on the cluster configuration and versions.  The error seems to indicate that the cluster is not able to find a matching version of the class in any jars in the classpath.

**Comment by mandar-degvekar** [comment]
It is resolved, issues with the pom.xml configuration.  Thanks for the response!!
