### ISSUE TITLE
Data of type SparkListenerEvent was dropped

### ISSUE THREAD

**Issue by koichino** [mspnp/spark-monitoring#149]
I configured spark-monitoring (ref: https://github.com/mspnp/spark-monitoring) and after that, they started to face the errors about SparkLoggingEvent on Log Analytics workspace as below.
I think Spark monitoring app has some issues leads these errors. This is not happening for only one specific environment but for multiple users, my colleague also faced a same error as .
We have already contacted Log Analytics team and they are saying the limit of customer fields are 500. So the Spark monitoring app are trying to add customer fields more than the limit.
Please consider avoiding Log Analytics # of fields limit.
 
<Error messages>
Warning:
The following fields' values message of type SparkLoggingEvent have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly. (1)
 
Error:
Data of type SparkListenerEvent was dropped: The number of custom fields 501 is above the limit of 500 fields per data type. See https://aka.ms/AA593as to find instructions for removing unnecessary custom fields for this type. (1)

**Comment by hallihan** [comment]
Information was added to the README at: https://github.com/mspnp/spark-monitoring#sparklistenerevent_cl to explain this behavior.  The library does not create/add fields, but is simply passing JSON formatted events from the underlying Spark framework and workload to Log Analytics. Concerns with the number of fields would have to be addressed at the Job or Spark framework layer, or the messages types could be excluded with creative use of [Filtering](https://github.com/mspnp/spark-monitoring/blob/main/docs/filtering.md).
