### ISSUE TITLE
Monitoring Pyspark Applications 

### ISSUE THREAD

**Issue by jugi92** [mspnp/spark-monitoring#152]
Hi, is it possible to monitor pyspark streams with this project? I can install the jars from the dependencies on the cluster, but then I would need to somehow call them via the Python APIs. Is that somehow possible? Thanks for any hints

**Comment by hallihan** [comment]
We do not currently have any plans to integrate the library with PySpark jobs, but if you or anyone in the community would like to develop that, it would be a welcome contribution.
