### ISSUE TITLE
Serializing Errors

### ISSUE THREAD

**Issue by iculda** [mspnp/spark-monitoring#159]
Hello for some reasons i got a lot of those events and no SparkListenerEvent_CL logs appears
`Error serializing SparkListenerEvent to JSON: SparkListenerJobStart(2,1638933194181,WrappedArray(org.apache.spark.scheduler.StageInfo@3ca3ca0c)`
It seems that is somewhat related with 
`exception_exception_class_s | java.util.ConcurrentModificationException
`
Configuration is identically with documentation
Can you guys point me to something?
Thank you

LE: It seems that is happening only on Databricks 9.1

**Comment by hallihan** [comment]
Can you reliably reproduce the error with the latest version of the code? If so is there more detail available, like a full callstack?

**Comment by hallihan** [comment]
Without a callstack there's not much further we can investigate here.
