### ISSUE TITLE
Log Analytics getting stuck for ever

### ISSUE THREAD

**Issue by databricksworld** [mspnp/spark-monitoring#168]
On the Spark driver, we see the intergration with the Log analytics get stuck for ever. The Spark driver thread dump says its getting stuck in the below thread:

sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:837)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:999)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
com.microsoft.pnp.client.GenericSendBuffer.send(GenericSendBuffer.java:76) => holding Monitor(java.lang.Object@1123518284})
com.microsoft.pnp.client.loganalytics.LogAnalyticsSendBufferClient.sendMessage(LogAnalyticsSendBufferClient.java:43)
com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender.append(LogAnalyticsAppender.java:65)
org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251) => holding Monitor(com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender@1805968929})
org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
org.apache.log4j.Category.callAppenders(Category.java:206) => holding Monitor(org.apache.log4j.spi.RootLogger@535862408})
org.apache.log4j.Category.forcedLog(Category.java:391)
org.apache.log4j.Category.log(Category.java:856)
org.slf4j.impl.Log4jLoggerAdapter.log(Log4jLoggerAdapter.java:581)
kafkashaded.org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.writeLog(LogContext.java:434)
kafkashaded.org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.info(LogContext.java:387)
kafkashaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.maybeSeekUnvalidated(SubscriptionState.java:381) => holding Monitor(kafkashaded.org.apache.kafka.clients.consumer.internals.SubscriptionState@686754004})
kafkashaded.org.apache.kafka.clients.consumer.internals.Fetcher.resetOffsetIfNeeded(Fetcher.java:716)
kafkashaded.org.apache.kafka.clients.consumer.internals.Fetcher.access$2700(Fetcher.java:128)
kafkashaded.org.apache.kafka.clients.consumer.internals.Fetcher$2.onSuccess(Fetcher.java:740)
kafkashaded.org.apache.kafka.clients.consumer.internals.Fetcher$2.onSuccess(Fetcher.java:728)

**Comment by hallihan** [comment]
This behavior may be addressed in #166 - If you still experience it with the latest code I would be interested to see another thread dump

**Comment by hallihan** [comment]
Closing this out since there's no update, feel free to open another issue if there is still a problem.
