### ISSUE TITLE
Recommendations on SparkListenerEvent_CL Filtering

### ISSUE THREAD

**Issue by mgfortes** [mspnp/spark-monitoring#182]
First - love this utility, so thank you.

Out of the box this utility, unfiltered, quickly gets to a point where logs stored exceed the 500 column threshold limitation for a log analytics workspace table due to constant additions of columns of the variety "modifiedConfigs_..." and "properties_spark/databricks/etc..." coming from SparkListenerJobStart and SparkListenerStageSubmitted event types .  Much of this content is useful but without being able to these columns the log analytics column limit and eventual data loss in the logs becomes unavoidable.  It would be really awesome if you could provide a means of filtering on these specific event types (and any others that may have variable column sets that I missed)

Thank you!

**Comment by hallihan** [comment]
Unfortunately, the variety of columns grew considerably after this library was first implemented. If you have an observability scenario that is impacted here, I recommend reaching out to the contact listed in the README for alternatives. https://github.com/mspnp/spark-monitoring/tree/l4jv2#monitoring-azure-databricks-in-an-azure-log-analytics-workspace
