### ISSUE TITLE
java.io.IOException: Error sending to Log Analytics

### ISSUE THREAD

**Issue by vamsikrish601** [mspnp/spark-monitoring#185]
Hi Team,

I am using the latest spark-monitoring script as part of data bricks jobs deployment but I am seeing below error, can you please suggest on the same?

Error in "Standard Error":

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Error sending to Log Analytics
java.io.IOException: Error sending to Log Analytics
Error sending to Log Analytics
java.io.IOException: Error sending to Log Analytics
Error sending to Log Analytics
java.io.IOException: Error sending to Log Analytics

NOTE:

spark-monitoring script is using the correct Azure Log Analytics Work space details.

Thanks,
Vamsi

**Comment by hallihan** [comment]
That log message looks like it is from a version of the jar built prior to #166 - can you confirm that the jar has been rebuilt and re-uploaded to the workspace with the most recent changes?   #166 added more detailed logging for error scenarios like this.

**Comment by hallihan** [comment]
Follow up details were not provided, closing.
