### ISSUE TITLE
Adding more loggers other than log4j

### ISSUE THREAD

**Issue by shivam-51** [mspnp/spark-monitoring#197]
I understand that the current solution only captures logs from `log4j` using `SparkLoggingEvent_CL` and `SparkMetric_CL`. I need to also send logs from python `logging` and `mlflow` is there a way to change the init script to do so?

**Comment by hallihan** [comment]
Further enhancements on this library are not planned. See the note in the README: https://github.com/mspnp/spark-monitoring/tree/l4jv2#monitoring-azure-databricks-in-an-azure-log-analytics-workspace
