### ISSUE TITLE
Missing Data Catalog Documentation

### ISSUE THREAD

**Issue by DataBach-maker** [mspnp/spark-monitoring#201]
Thanks for providing the `logAnalyticsDeploy.json` with a extensive list of queries. I would like to extend this list and add more queries. Could you provide documentation or a link to documentation about what the diffrent variables such as value_d, name_d refer to exactly ?

**Comment by hallihan** [comment]
These values are set by the Spark runtime and can change over time as the platform changes.  https://spark.apache.org/docs/latest/monitoring.html#executor-task-metrics might be a good starting point.
