### ISSUE TITLE
Add DBR > 11 support please!

### ISSUE THREAD

**Issue by SamarpanRai-TomTom** [mspnp/spark-monitoring#204]
> This library supports Azure Databricks 10.x (Spark 3.2.x) and earlier (see [Supported configurations](https://github.com/mspnp/spark-monitoring/blob/main/README.md#supported-configurations)). Azure Databricks 11.0 includes [breaking changes](https://learn.microsoft.com/azure/databricks/release-notes/runtime/11.0#log4j-is-upgraded-from-log4j-1-to-log4j-2) to the logging systems that the spark-monitoring library integrates with. The work required to update the spark-monitoring library to support Azure Databricks 11.0 (Spark 3.3.0) and newer is not currently planned.

We use DBR > 11 and this support would be super valuable to us!

**Comment by JonGerrand** [comment]
Ditto. Note that Unity Catalogue GA also has a dependency on DBR >= 11.1!

**Comment by mayurkatariya** [comment]
PROS also has the same issue. 
Looking for support with Azure DBR 11.0
