### ISSUE TITLE
Log4j appender thread pool needs to be shutdown

### ISSUE THREAD

**Issue by djoyce-eis** [mspnp/spark-monitoring#27]
The GenericSendBuffer class has an Executor that log publishing tasks are submitted to.

Any application that uses the library will hang for over a minute on completion waiting for this Executor to auto-shutdown

Therefore, the library should expose the ability to shutdown this Executor on completion of a job

At present the Executor it package private and therefore clients cannot access it to shut it down

**Comment by nithinpnp** [comment]
we are working on this

**Comment by nithinpnp** [comment]
@djoyce-eis  -- are you using job cluster or regular spark ?

**Comment by djoyce-eis** [comment]
I believe that I ran this via a Notebook

**Comment by djoyce-eis** [comment]
Sorry closed by mistake, reopened

**Comment by nithinpnp** [comment]
Sorry, My question was. once you choose a notebook . do you choose a new cluster or choose an existing cluster. 
We have implemented close in appender. https://github.com/mspnp/spark-monitoring/pull/32.
This close can be invoked by waiting for the streaming query to terminate and invoke log manager .shutdown.
     query.awaitTermination();
    LogManager.shutdown()

This works when you spin a cluster on demand for a job.  But when a long running cluster gets run , this statement will kill the log4j appenders across the cluster and logs of other concurrent jobs will not be generated.

**Comment by djoyce-eis** [comment]
I believe I found the issue when creating a new cluster.

I don't think killing appenders for other jobs would be desirable, if that is the case then I don't think we could use this.

Is there any way to constrain this to a per-job level only?

**Comment by atoakley** [comment]
@djoyce-eis 
- Is this an Interactive Cluster or a Job Cluster?
- Did you configure the cluster as a whole to log to Log Analytics or only your individual notebook?

I forgot to go back and implement .Close() on the appender, so we merged the code in PR #32 to shut down the executor.  So, in theory, if Spark shuts down the appender properly, it should shut down the executor.  Please let me know if it fixes the issue you are seeing.

**Comment by atoakley** [comment]
@djoyce-eis If the issue persists, please reopen this issue.
