### ISSUE TITLE
provide an example on how to use this logging framework within a Databricks notebook

### ISSUE THREAD

**Issue by azeltov** [mspnp/spark-monitoring#28]
I am trying to use the logging framework with in the DBX notebook, however when i use the logger to write any type of log(warn,debug) it does not write to my loganalytics workspace. It does work using the sample job/jar you provided. If possible can you provide an example on how to use this logging framework within a Databricks notebook. Thank you!
![image](https://user-images.githubusercontent.com/5873303/55516326-e913ed80-563a-11e9-83ac-56300ea405f6.png)

**Comment by djoyce-eis** [comment]
Have you set the environment variables required for the the Log Analytics authentication?

**Comment by atoakley** [comment]
The reason it works in the sample is because we have configured log4j to log from our sample job package.  To use this from a Databricks Notebook, you will need to do the same.  There are a couple of options.

- You can configure the whole cluster to log to Log Analytics, which will include notebooks
- You can include the code below in every Databricks Notebook.  It should work for any notebook because it pulls the class name from the notebook when it runs, but this is lightly tested, so YMMV. 😄 
```scala
%scala
import com.microsoft.pnp.util.TryWith
import com.microsoft.pnp.logging.Log4jConfiguration
import java.io.ByteArrayInputStream
import org.slf4j.LoggerFactory

val className = getClass.getName
val log4jConfig = s"""
log4j.appender.logAnalytics=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
log4j.appender.logAnalytics.layout=com.microsoft.pnp.logging.JSONLayout
log4j.appender.logAnalytics.layout.LocationInfo=false
log4j.additivity.$className=false
log4j.logger.$className=INFO, logAnalytics
"""

TryWith(new ByteArrayInputStream(log4jConfig.getBytes())) {
  stream => {
    Log4jConfiguration.configure(stream)
  }
}

val logger = LoggerFactory.getLogger(getClass)
logger.info("Info message")
logger.warn("Warn message")
logger.error("Error message")
```

Let me know if this doesn't work for you.

**Comment by mpsingh24** [comment]
> The reason it works in the sample is because we have configured log4j to log from our sample job package. To use this from a Databricks Notebook, you will need to do the same. There are a couple of options.
> 
> * You can configure the whole cluster to log to Log Analytics, which will include notebooks
> * You can include the code below in every Databricks Notebook.  It should work for any notebook because it pulls the class name from the notebook when it runs, but this is lightly tested, so YMMV. 😄
> 
> ```scala
> %scala
> import com.microsoft.pnp.util.TryWith
> import com.microsoft.pnp.logging.Log4jConfiguration
> import java.io.ByteArrayInputStream
> import org.slf4j.LoggerFactory
> 
> val className = getClass.getName
> val log4jConfig = s"""
> log4j.appender.logAnalytics=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
> log4j.appender.logAnalytics.layout=com.microsoft.pnp.logging.JSONLayout
> log4j.appender.logAnalytics.layout.LocationInfo=false
> log4j.additivity.$className=false
> log4j.logger.$className=INFO, logAnalytics
> """
> 
> TryWith(new ByteArrayInputStream(log4jConfig.getBytes())) {
>   stream => {
>     Log4jConfiguration.configure(stream)
>   }
> }
> 
> val logger = LoggerFactory.getLogger(getClass)
> logger.info("Info message")
> logger.warn("Warn message")
> logger.error("Error message")
> ```
> 
> Let me know if this doesn't work for you.

This did not work for me. I see cluster logs going to Log Analytics workspace, but not the notebook logs. Steps followed:
1. Created a new cluster to run listeners.sh as Init Script
2. Configured logging in notebook: 
   // Configure our logging
    TryWith(getClass.getResourceAsStream("/log4j.properties")) {
      stream => {
        Log4jConfiguration.configure(stream)
      }
    }
3. Logged events which did not come up in the Log Analytics workspace:
val logger = LoggerFactory.getLogger(getClass)
logger.info("Info message")
logger.warn("Warn message")
logger.error("Error message")

Would appreciate any help

**Comment by amandal1810** [comment]
was anyone able to achieve this?

**Comment by atoakley** [comment]
@mpsingh24 You are not configuring logging the same way as the example code. You are trying to load a resource from the classpath. If you configure the logging system the way the sample code does, it will work.

**Comment by eparizzi** [comment]
I have to give my vote that it's not clear how to make this work from a notebook. I've followed all the steps in the project readme. I've set my cluster to run the listeners.sh script.

Now, after all that. What's the code to log from a notebook command?

@atoakley You said there are 2 options, one is to set the whole cluster to log to Log Analytics, which will include notebooks, but you haven't mentioned how to do that? Just following the readme and setting the listeners.sh script as a init script of the cluster is enough?
If so, then what's the actual code to get an instance of the logger?

**Comment by atoakley** [comment]
@eparizzi Did the Scala code above not work for you? It shows how to get an instance of a logger from SLF4j.

**Comment by eparizzi** [comment]
> @eparizzi Did the Scala code above not work for you? It shows how to get an instance of a logger from SLF4j.

Oh ok, yes, that worked. I thought that was the snippet for the 2nd method (include the snippet in every Databricks notebook). 

Anyway, I do see Spark logs and metrics, but I don't see the custom info, warn and error. Where are those supposed to be?

**Comment by atoakley** [comment]
Yes. That snippet is for the 2nd method. If you are using that method, adding the following line into your customer log4j settings should work.

log4j.appender.logAnalytics.logType=MyCustomLog

This should create a Log Analytics table called MyCustomLog_CL.

**Comment by eparizzi** [comment]
> Yes. That snippet is for the 2nd method. If you are using that method, adding the following line into your customer log4j settings should work.
> 
> log4j.appender.logAnalytics.logType=MyCustomLog
> 
> This should create a Log Analytics table called MyCustomLog_CL.

Great, that worked. Thanks.

So, how would one go to avoid that snippet in every notebook and just set everything up for the whole cluster as you mentioned above?

**Comment by atoakley** [comment]
@eparizzi It would be general log4j configuration. If you look at the sample job, the log4j configuration is limited to that particular job's class. You would want to do something similar, but at a package level. You would need to see what the Databricks package name is for notebooks and use that.

**Comment by eparizzi** [comment]
> @eparizzi It would be general log4j configuration. If you look at the sample job, the log4j configuration is limited to that particular job's class. You would want to do something similar, but at a package level. You would need to see what the Databricks package name is for notebooks and use that. Then you should be able to get a logger in your notebook from SLF4j and it should work, in theory.

Ok, I'm not very familiar with log4j. Anyway the snippet on the notebook should be fine.

One last question, is there a way to add custom properties that can be used in filters in Log Analytics by using the info/warn/error methods?

**Comment by eparizzi** [comment]
> @eparizzi It would be general log4j configuration. If you look at the sample job, the log4j configuration is limited to that particular job's class. You would want to do something similar, but at a package level. You would need to see what the Databricks package name is for notebooks and use that. Then you should be able to get a logger in your notebook from SLF4j and it should work, in theory.

@atoakley Great, thanks.

One last question, is there a way to add custom properties that can be used in filters in Log Analytics by using the info/warn/error methods?

**Comment by atoakley** [comment]
@eparizzi Well, any log4j 2.x will not work in Spark since it is using log4j 1.2, which is very old. In addition to that, using log4j directly is not ideal since Spark is using SLF4J as the logging "interface". There is not a sample in this repo, but you can see how to add additional fields to a logging message [here](https://github.com/mspnp/azure-databricks-streaming-analytics/blob/master/azure/AzureDataBricksJob/src/main/scala/com/microsoft/pnp/StreamingMetricsListener.scala). This project was a reference architecture that had the precursor code to this library. This part was ported over virtually unchanged. However, be aware that the underlying bits under the MDC are not as thread-safe as one would like, so make sure the MDC isn't long lived.

**Comment by eparizzi** [comment]
> @eparizzi Well, any log4j 2.x will not work in Spark since it is using log4j 1.2, which is very old. In addition to that, using log4j directly is not ideal since Spark is using SLF4J as the logging "interface". There is not a sample in this repo, but you can see how to add additional fields to a logging message [here](https://github.com/mspnp/azure-databricks-streaming-analytics/blob/master/azure/AzureDataBricksJob/src/main/scala/com/microsoft/pnp/StreamingMetricsListener.scala). This project was a reference architecture that had the precursor code to this library. This part was ported over virtually unchanged. However, be aware that the underlying bits under the MDC are not as thread-safe as one would like, so make sure the MDC isn't long lived.

Ok, after digging a bit through the code I found how to do it. I'd like this to have an easier API though.

For those interested, here's a full example to log from a notebook with custom properties, after the cluster's been properly setup as explained in the readme:

```scala
import com.microsoft.pnp.util.TryWith
import com.microsoft.pnp.logging.Log4jConfiguration
import com.microsoft.pnp.logging.MDCCloseableFactory
import java.io.ByteArrayInputStream
import org.slf4j.LoggerFactory
import java.util.HashMap

val className = getClass.getName
val log4jConfig = s"""
log4j.appender.logAnalytics=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
log4j.appender.logAnalytics.layout=com.microsoft.pnp.logging.JSONLayout
log4j.appender.logAnalytics.layout.LocationInfo=false
log4j.appender.logAnalytics.logType=CUSTOM_LOG_NAME
log4j.additivity.$className=false
log4j.logger.$className=INFO, logAnalytics
"""

TryWith(new ByteArrayInputStream(log4jConfig.getBytes())) {
  stream => {
    Log4jConfiguration.configure(stream)
  }
}

val logger = LoggerFactory.getLogger(getClass)
val runId = 23
val env = "QA"

val context = new HashMap[String, AnyRef]()
context .put("runId", runId.toString)
context .put("env", env)

val mdcFactory: MDCCloseableFactory = new MDCCloseableFactory()
TryWith(this.mdcFactory.create(context ))(
  c => {
    this.logger.info("Info with context")
    this.logger.warn("Warn with context")
    this.logger.error("Error with context")
  }
)
```

**Comment by atoakley** [comment]
@eparizzi Unfortunately, do to the threading issues in the underlying libraries, and the abstract nature of SLF4J, this was really the only safe way to do it. Logging from a notebook was not a primary goal of the library, so we didn't focus on the developer experience. Please open a PR with any suggestions and I would be happy to look at it.

**Comment by eparizzi** [comment]
> @eparizzi Unfortunately, do to the threading issues in the underlying libraries, and the abstract nature of SLF4J, this was really the only safe way to do it. Logging from a notebook was not a primary goal of the library, so we didn't focus on the developer experience. Please open a PR with any suggestions and I would be happy to look at it.

I understand.

We tried to migrate to a proper Spark application, but we had all sort of issues with the dbutils class. Specifically finding a proper way to use it that will work when developing locally using databricks-connect and also when running it on an Azure Databricks job.
Where can I ask about this?

**Comment by mcheedle** [comment]
We don't use Scala, but we essentially let it try to get a log4j connection, then fail to another python logger. Seems like you should be able to do something similar:

`class OurLogger:
	def __init__(self, log4jLogger):
		try:
			self.logger = log4jLogger.LogManager.getLogger(__name__)
			
		except Exception as e:
			import logging
			self.logger = logging.getLogger(__name__)
			self.logger.info(str(e))
`

**Comment by atoakley** [comment]
You are using Python, which has a limitation with regard to logging from Spark. See #50 
I'll close this issue since you have gotten this to work. If you need to reopen it, please do so.

**Comment by shbhmpthk** [comment]
is there any way to disable all the logging done by spark by default and send only custom logs to Azure Log Analytics? I think the logging is adversely impacting my cluster performance.
