### ISSUE TITLE
No SparkMetric_CL created in Log Analytics workspace ( SparkListenerEvent_CL available in workspace)

### ISSUE THREAD

**Issue by abmehra** [mspnp/spark-monitoring#29]
Followed the steps outlined in the document but not able to view SparkMetric_CL in workspace even after cluster is up and running.

**SparkListenerEvent_CL**  is getting created so I am assuming  cluster environment variables etc is all correct.

**Comment by cfarre** [comment]
@abmehra we have PR to fix this issue. Meanwhile the PR is not approved all you have to do is open the pom.xml and change spark.version to 2.4.0  <spark.version>2.4.0</spark.version>. recycle the dependencies in the UI rebuild the project. Delete the old jars and copy again the new created jars. start your cluster.

**Comment by viboga** [comment]
verified that the fix works.

**Comment by cfarre** [comment]
@abmehra @viboga this PR has been approved that fixes this issue.

**Comment by atoakley** [comment]
Fixed by #30

**Comment by Musham-Aj** [comment]
@cfarre After adding the version '2.4.0 ', Still, We are facing the same issue. Couldn't able to retrieve the logs in the Log Analytics workspace. We have changed the POM file as you mentioned. 

Here, I have tried out using the Spark version from 7.4 to 8.3. With all the versions, I have tried. Can you please help me out on this?
