### ISSUE TITLE
Release publish in public repository

### ISSUE THREAD

**Issue by wankes2000** [mspnp/spark-monitoring#42]
Hi

Do you plan to publish a release of this library in a public artifact repostiory like Maven Central in a near future? I want to use this lib in one of my projects, but it's very complicate for me to manage dependencies if the lib is not published in a public artifact repository.

Thank you

**Comment by atoakley** [comment]
@wankes2000 We will look into doing this.

**Comment by Duber** [comment]
Any news on this ? Why was the issue closed ?
