### ISSUE TITLE
Grafana dashboard panel is showing Request Error

### ISSUE THREAD

**Issue by muhsinmp** [mspnp/spark-monitoring#44]
I am using Azure instance of Grafana, and i am trying to setup monitoring for Azure databricks using grafana dashboards. I have used the link : https://docs.microsoft.com/bs-latn-ba/azure/architecture/databricks-monitoring/dashboards to setup the grafana and its dashboard. But when i completed the setup, the panels in the Grafana dashboard is showing “Request Error” on top it. When i looked in to the query of the panel, its showing "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) as error.
The syntax error which i could find from the browser console is : 
'extend' operator: Failed to resolve scalar expression named 'Properties_spark_metric_namespace_s'
![Grafana](https://user-images.githubusercontent.com/10824070/60939432-4af88900-a2f5-11e9-8ea5-764ca203bc8d.jpg)

**Comment by robert4os** [comment]
Same issue. Interestingly the same query works, if I copy and paste the code in a new dashboard, where I create a new query.

**Comment by cfarre** [comment]
@muhsinmp @robert4os 
I am investigating, meanwhile just to unblock you, try the following. Click on your cluster, then in spark config add the below entry where yourMetricsNamespace is a logical name.
this will fix the error if if you stop the cluster and remove the entry

spark.metrics.namespace yourMetricsNamespace

**Comment by robert4os** [comment]
@cfarre
Your message is confusing, shall we 'add' or 'remove' the entry? In any case I do not see how this would be relevant.

Anyhow, I have found the problem with the dashboard... a number of problems really, but the main problem is that the template comes with an absolute time frame in the JSON Model (time/from/to). Changing this to 'now-24h' and 'now' fixes the problem.  

best regards, Robert

**Comment by cfarre** [comment]
@robert4os thanks for your solution. the time picker is the issue. we will fix it. I meant adding the metrics namespace which is a good practice anyway in spark config. that would put the property field Properties_spark_metric_namespace_s in log analytics. but this is not necessary because if does not exist we pick app id. 

spark.metrics.namespace yourMetricsNamespace

**Comment by atoakley** [comment]
Closed by #48
