### ISSUE TITLE
I am getting the below error while starting the cluster. 625514421484409 is my workspaceid

### ISSUE THREAD

**Issue by atoakley** [mspnp/spark-monitoring#45]
I am getting the below error while starting the cluster. 625514421484409 is my workspaceid

Init Script Failure: Init script dbfs:/databricks/monitoring-staging/listeners.sh failed: /625514421484409/databricks/monitoring-staging/listeners.sh: No such file or directory.

![cluster_err](https://user-images.githubusercontent.com/33412636/61347942-6ecf4800-a87c-11e9-8d49-e04db7c3b7b5.jpg)

_Originally posted by @csmurthy in https://github.com/mspnp/spark-monitoring/issues/43#issuecomment-512100897_

**Comment by atoakley** [comment]
@csmurthy Did you copy the jars and associated script files to the dbfs:/databricks/monitoring-staging directory for your workspace?

**Comment by csmurthy** [comment]
Thanks Andrew. I realized I copied the files to a different workspace. I'll fix that and try again

**Comment by atoakley** [comment]
@csmurthy I'm going to close this issue, but if you continue to have problems, please reopen.
