### ISSUE TITLE
Failure building the maven project.

### ISSUE THREAD

**Issue by Playmaker05** [mspnp/spark-monitoring#46]
I am very new in this and I am still learning about IT. I am trying to follow all the steps but I am dealing with an error in building the Jar files and I cannot find the answer. If someone could help me I will be very glad.

I am executing the maven package build phase in Intellij but the building is failing. The error says "Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.2:compile (default) on project spark-listeners: Execution default of goal net.alchim31.maven:scala-maven-plugin:3.4.2:compile failed.: CompileFailed ".

I also have this error about compiler in mirror not found:
![Untitled err](https://user-images.githubusercontent.com/47570663/61560415-d5e22d80-aa31-11e9-9a6c-ea1ad1361358.png)

**Comment by mpfishe2** [comment]
Did you try going to `.\spark-monitoring\src` and execute:  
```bash
mvn clean package
```
This worked for me and it built perfectly. I think if you try and build them one by one it will fail because it will be missing some dependencies.

**Comment by Playmaker05** [comment]
Thanks for your answer mpfishe2.

I am working with IntelliJ but I also tried in command line but still have the same problem. I also tried build all and one by one but I am receiving the same error:
 " Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.2:compile (default) on project spark-listeners: Execution default of goal net.alchim31.maven:scala-maven-plugin:3.4.2:compile failed.: CompileFailed -> [Help 1]"

![Untitled err2](https://user-images.githubusercontent.com/47570663/61641248-6acc6d00-ac64-11e9-9c8b-8a1cdbb058f8.png)
