### ISSUE TITLE
Create Dropwizard gauges or counters in your application code. You can use the UserMetricsSystem class defined in the monitoring library. The following example creates a counter named counter1.

### ISSUE THREAD

**Issue by vikas678123** [mspnp/spark-monitoring#47]
I am new to java and need help in understanding how can i use Dropwizard to create counters and it says application code where is the code i can see.Can you help me understand in detail on this point

**Comment by atoakley** [comment]
There is a sample job located [here](https://github.com/mspnp/spark-monitoring/blob/master/src/spark-jobs/src/main/scala/com/microsoft/pnp/samplejob/StreamingQueryListenerSampleJob.scala) that shows how to use the UserMetricsSystem. Please reopen this issue if you have any more questions.
