### ISSUE TITLE
Spark-Listener dependency issue

### ISSUE THREAD

**Issue by johanneskre97** [mspnp/spark-monitoring#49]
Hi project team,

we tried to compile a jar file, but there is an issue with the dependency.
We are using the following comand to resolve the dependencies:
`mvn dependency:resolve`

.. and recieve the following error message:

> [ERROR] Failed to execute goal on project spark-jobs: Could not resolve dependencies for project com.microsoft.pnp:spark-jobs:jar:1.0-SNAPSHOT: Could not find artifact com.mi
> crosoft.pnp:spark-listeners:jar:1.0-SNAPSHOT -> [Help 1]

**Comment by atoakley** [comment]
@johanneskre97 See Issue #46. Those instructions will build the two jar files you need. The spark-jobs jar file is only a sample job. It is not needed to collect diagnostic information. We are currently in the process of updating the documentation to make this more clear.

**Comment by atoakley** [comment]
@johanneskre97 If you are still having trouble building the library, please reopen this issue.
