### ISSUE TITLE
Logging to Azure Log Analytics workspace through Scala Notebook

### ISSUE THREAD

**Issue by mpsingh24** [mspnp/spark-monitoring#51]
This did not work for me through Scala Notebook. I see cluster logs going to Log Analytics workspace, but not the notebook logs. Steps followed fir DBR Runtime 5.5 LTS:

Created a new cluster to run listeners.sh as Init Script
Configured logging in notebook:
// Configure our logging
TryWith(getClass.getResourceAsStream("/log4j.properties")) {
stream => {
Log4jConfiguration.configure(stream)
}
}
Logged events which did not come up in the Log Analytics workspace:
val logger = LoggerFactory.getLogger(getClass)
logger.info("Info message")
logger.warn("Warn message")
logger.error("Error message")
Am I missing something here? Would appreciate any help.

**Comment by atoakley** [comment]
@mpsingh24 Closing this and answering in #28
