### ISSUE TITLE
support for scala 2.12

### ISSUE THREAD

**Issue by gobiviswanath** [mspnp/spark-monitoring#62]
I implemented Grafana monitoring tool with getting metrics from Databricks through Azure Log Analytics and Azure Monitor as specified here: https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/dashboards
This library is based on Scala 2.11 and Spark 2.4.3.

I guess my previous cluster where the monitoring solution was working was runtime 5.5. But as I updated runtime of my cluster to the latest version,  based on Scala 2.12, the monitoring tool does not work. More specifically, it looks like that there is a problem on the init bash (spark-monitoring.sh).

I wonder if you guys have a plan to update the spark-monitoring pacakge according to new version of Databricks runtime.

**Comment by atoakley** [comment]
@gobiviswanath What version of the Databricks runtime is failing? I suspect the spark-monitoring.sh init script is failing because it is looking for jar files that do not exist because we do not build for Scala 2.12. It should be fairly easy to add a new profile in the parent pom that will support Scala 2.12.

**Comment by atoakley** [comment]
@gobiviswanath I checked on the different versions of the Databricks 6.x clusters, and I think the SPARK_SCALA_VERSION environment variable may be incorrectly reporting the version of Scala. The jars for the runtime seem to be Scala 2.11. Can you try the [updated script](https://github.com/mspnp/spark-monitoring/blob/andrew/spark-version-fix/src/spark-listeners/scripts/spark-monitoring.sh) and see if it fixes the issue?

**Comment by atoakley** [comment]
@gobiviswanath Hopefully this fixed your issue. Closing this now.

**Comment by Smarker** [comment]
Also, @gobiviswanath as I was going over the databricks docs I saw:

> Although Scala 2.12 is available as an experimental feature in Apache Spark 2.4, it is not supported in Databricks Runtime 6.3.

This is mentioned [here](https://docs.databricks.com/release-notes/runtime/6.3.html#system-environment).

So even if you build for `Scala 2.12` with databricks runtime 6.0-6.3, I don't think it's ready yet for databricks.
