### ISSUE TITLE
Can't build sample project

### ISSUE THREAD

**Issue by eparizzi** [mspnp/spark-monitoring#64]
Readme says that I should be able to open the sample project's pom located at `sample/spark-sample-job/pm.xml` and it should be able to build using maven.

I don't have much experience with Java and Maven. I'm using IntelliJ IDEA. I'm able to build the other projects, but the sample one says:
`Cannot resolve com.microsoft.pnp:spark-listeners_2.11_2.4.3:1.0.0`

Looking in the Maven repository there isn't a package by that name so I'm assuming this should come from project in /src. 

The sample pom.xml has this but I'm not sure how to tell it where to find that dependency
```
      <dependency>
            <groupId>com.microsoft.pnp</groupId>
            <artifactId>spark-listeners_${scala.compat.version}_${spark.version}</artifactId>
            <version>${spark.listeners.version}</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by atoakley** [comment]
@eparizzi If you just want to build the library and the sample, you can follow the directions and it will build them both. If you want to build them in the IDE, you will need to run the Maven install goal on the Spark Listener project before building the sample project.

**Comment by eparizzi** [comment]
> @eparizzi If you just want to build the library and the sample, you can follow the directions and it will build them both. If you want to build them in the IDE, you will need to run the Maven install goal on the Spark Listener project before building the sample project.

I've followed the README and successfully built the project (src/pom.xml). But the sample project is on another project (sample/spark-sample-job/pom.xml) and that pom.xml file includes this dependency:

```xml
<dependency>
  <groupId>com.microsoft.pnp</groupId>
  <artifactId>spark-listeners_${scala.compat.version}_${spark.version}</artifactId>
  <version>${spark.listeners.version}</version>
  <scope>provided</scope>
</dependency>
´´´

But the spark-listeners project is not part of the sample project so where is it suppose to find it?

Just clone a fresh copy of the repo, open the sample project pom with IntelliJ and try to build. It fails because it can't find this spark-listeners project.

**Comment by eparizzi** [comment]
Got it working. Problem was I was using IntelliJ IDEA but wasn't using maven to build the projects.
