### ISSUE TITLE
How to use this in a SBT project?

### ISSUE THREAD

**Issue by eparizzi** [mspnp/spark-monitoring#66]
How can I make use of this in a project that uses SBT instead of Maven? The sample shows how to do it on Maven but I can't seem to get it working on my SBT project.

Thanks

**Comment by sidtandon2014** [comment]
@eparizzi  I have compiled this using maven and used the JAR as unmanaged dependency

But you can definitely convert project type to sbt and fix the issues

**Comment by jocontr** [comment]
Closing this issue as it is a feature request.
