### ISSUE TITLE
Additional LogAnalyticsAppender not working for automated clusters

### ISSUE THREAD

**Issue by mikanyg** [mspnp/spark-monitoring#67]
I have an issue getting _spark-monitoring_ to work in automated clusters running a python notebook job. The python notebook has both python code and some scala code running in seperate `%scala` command. Both python and scala code needs to log events that should be forwarded to log analytics. 

Using the default cluster init script from this repo, and configuring it like in the README.md works as expected.

But I have tweaked the log4j config in the cluster init script `spark-monitoring.sh` like in this code snippet

```
...
tee -a ${LOG4J_CONFIG_FILE} << EOF
# logAnalytics
log4j.appender.logAnalyticsAppender=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
log4j.appender.logAnalyticsAppender.filter.spark=com.microsoft.pnp.logging.SparkPropertyEnricher
log4j.appender.logAnalyticsAppender.Threshold=WARN

# pipelineLog
log4j.logger.pipelineLog=INFO, pipelineAppender
log4j.additivity.pipelineLog=false

# pipelineAppender
log4j.appender.pipelineAppender=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
log4j.appender.pipelineAppender.filter.spark=com.microsoft.pnp.logging.SparkPropertyEnricher
log4j.appender.pipelineAppender.layout=com.microsoft.pnp.logging.JSONLayout
log4j.appender.pipelineAppender.layout.LocationInfo=false
log4j.appender.pipelineAppender.logType=PipelineLoggingEvent
log4j.appender.pipelineAppender.Threshold=INFO
EOF

echo "END: Updating $LOG4J_CONFIG_FILE with Log Analytics appender"
...
```
Basically I want to only forward log events of log level **WARN** to log analytics by setting a Threshold on the default `logAnalyticsAppender` used by the `rootCategory` logger. Then I want a seperate logger called `pipelineLog` which forwards log events of log level **INFO** to a new specific table called `PipelingLoggingEvent` in log analytics. 

The log4j config shown in the above snippet works fine when running the notebook in an interactive cluster, but when scheduling it using jobs and automated clusters it does not work. Nothing gets send when using the `pipelineLog` logger from either python or scala code.

Both the interactive cluster and the automated clusters are using the revised cluster init script and the Databricks 5.5 LTS runtime. 

Hope to get some insight into why interactive clusters and automated clusters behave differently with this log4j config.

**Comment by atoakley** [comment]
@mikanyg Are there any indications in the logs that there may be something wrong? I would have to look into what the differences are between the two. As long as Spark is the same on both, that's all this library interacts with, so it should work.

**Comment by mikanyg** [comment]
All log entries can be found in the log4j log file, when running in both interactive and automated clusters, I cant identify any issues regarding log4j config.

If you have any things I should look for, I'll try to help, but for now I cant figure out why they behave differently using the same cluster init script.

**Comment by jocontr** [comment]
Closing issue due to no-repro. Please reopen is additional information is available.
