### ISSUE TITLE
Uncaught exceptions are sometimes not logged due to send buffer

### ISSUE THREAD

**Issue by stewartadam** [mspnp/spark-monitoring#71]
The stack trace from uncaught exceptions in jobs sometimes (more often than not) never reach Log Analytics because of the 5000ms/25M log buffer implemented in the underlying layers of the appender.

The `LogAnalyticsAppender` log4j appender implementation doesn't expose the fact that it is buffering, so even when immediate flush is set to true (the default), the underlying classes buffer the log messages. When a DataBricks job is killed due to an uncaught exception, it appears the last few buffered messages (including stack trace) get lost along with it.

We've somewhat worked around this by adding `LogManager.shutdown()` to a try-catch block in the job logic, however this appears to have side effects we are still investigating -- my current hunch is that this call causes all other (e.g. cluster infra logs) to stop flowing as well after the job terminates.

Tangentially related - it looks like the buffering code was refactored at one point and `LogAnalyticsSendBufferClient` has references to the 5000ms/25M but those aren't used anywhere, and are in fact controlled by the `LogAnalyticsSendBuffer` instance.

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [226337](https://dev.azure.com/ceapex/pnp/_workitems/edit/226337)

**Comment by jeremy010203** [comment]
Hi @jocontr ,
do you have news about the resolution of this issue? (I cannot access the linked Bug ID)
We have the same problem on our environment.
Thanks

**Comment by hallihan** [comment]
Some cases of this error should be fixed by #119.  Please open a new issue with additional details if you still see the behavior with the latest changes.
