### ISSUE TITLE
Running multiple jobs on same cluster throwing error

### ISSUE THREAD

**Issue by sidtandon2014** [mspnp/spark-monitoring#72]
I am trying to run multiple jobs with different log type, but its throwing an error

> Task com.microsoft.pnp.client.loganalytics.LogAnalyticsSendBufferTask@750db652 rejected from java.util.concurrent.ThreadPoolExecutor@6d69d47c[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 51]

` 
def getLogger(queueName: String) : Logger = {

    val className = getClass.getName
    val log4jConfig =
                s"""
          log4j.appender.logAnalytics=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
          log4j.appender.logAnalytics.layout=com.microsoft.pnp.logging.JSONLayout
          log4j.appender.logAnalytics.layout.LocationInfo=false
          log4j.appender.logAnalytics.logType=Test_${queueName.replaceAll("-","_")}
          log4j.additivity.$className=false
          log4j.logger.$className=INFO, logAnalytics
          """
`

**Comment by jocontr** [comment]
@sidtandon2014 ; apologies for the delay. Is this still an issue? If so could you provide more details/logs/etc. in order for us to be able to reproduce the issue?

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [226346](https://dev.azure.com/ceapex/pnp/_workitems/edit/226346)

**Comment by hallihan** [comment]
Reviewing old issues, since additional details were not provided, I'm going to close this.  Feel free to reopen if more details and logs can be shared.
