### ISSUE TITLE
Docker based build statement for sample project not working on windows

### ISSUE THREAD

**Issue by rahulguptakota** [mspnp/spark-monitoring#73]
Command: 
docker run -it --rm -v %cd%/spark-monitoring/sample/spark-sample-job:/spark-monitoring -v "%USERPROFILE%/.m2":/root/.m2 maven:3.6.1-jdk-8 mvn clean install -P scala-2.11_spark-2.4.3

From(tried):
\..\
\..\spark-monitoring
\..\spark-monitoring\sample\spark-sample-job

Output:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.115 s
[INFO] Finished at: 2020-03-03T23:31:18Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "scala-2.11_spark-2.4.3" could not be activated because it does not exist.
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Can you please help me identify what should be changed? It seems that maven is not able to find the pom file.

**Comment by jocontr** [comment]
Hi @rahulguptakota could you confirm that your deployment sequence cannot find the POM file located here? (https://github.com/mspnp/spark-monitoring/blob/master/sample/spark-sample-job/pom.xml)

If so could you provide the entire deployment log for us to review?

Closing for now as a no-repro. Please reopen if issue persists.
