### ISSUE TITLE
Unable to build jar for spark-listeners-loganalytics

### ISSUE THREAD

**Issue by viveksharma57** [mspnp/spark-monitoring#74]
Hi

I am unable to build the second jar (for spark-listeners-loganalytics). 

When I do maven build, build completes successfully but when I create jar using Maven install, I get dependency issue on com.microsoft.pnp.

Error that I get is 

> Failed to get dependencies for com.microsoft.pnp: spark-listeners_2.11_2.4.4: Failed to read artifact descriptor

Tried to find some solutions over internet but no luck so far.

Any help would be greatly appreciated.

Thanks

**Comment by jocontr** [comment]
Hi @viveksharma57 a brief search lead to various ideas in order to fix this issue. Among these I found "mvn -U clean install". Could you provide with a complete build log for us to review?

Closing this issue as no-repro for now.
