### ISSUE TITLE
Data of type SparkListenerEvent was dropped: 500 fields limit reached

### ISSUE THREAD

**Issue by jdocampo** [mspnp/spark-monitoring#75]
I have seen in my azure log analytics workspace errors like this one:

Data of type SparkListenerEvent was dropped: The number of custom fields 501 is above the limit of 500 fields per data type. See https://aka.ms/AA593as to find instructions for removing unnecessary custom fields for this type.
--

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [226370](https://dev.azure.com/ceapex/pnp/_workitems/edit/226370)

**Comment by hallihan** [comment]
@jdocampo - If you're still tracking this, do you have any specific examples of workload or messages that triggered the error, or any additional context around the log?  The Log Analytics ingestion API has a hard limit here and it appears that it will expand any top-level json fields in the content to custom fields.  This error seems to imply that something is sending a json blob with a large number of top-level fields.  Some additional detail would help track down if there's anything we can do to mitigate from the library's perspective.  Thanks!

**Comment by hallihan** [comment]
I'm going to close this one out as "by-design".  If there's a valid use case for using more than 500 top level fields, or if this is coming from something native to the Spark subsystem, we can investigate again if more details are available.

**Comment by guoguo5551** [comment]
@hallihan @jocontr I have same problem as title. My issue metric is SparkListenerEvent(Databricks application log) I can provide additional detail to track down for this issue but I need to know what kind of data should I provide to you for further investigation? Thanks1
