### ISSUE TITLE
How to log from a notebook with custom properties

### ISSUE THREAD

**Issue by NarsingManda** [mspnp/spark-monitoring#78]
Hi to all,

Actually we are using log4j to log to errors but our custom logs are mixed with spark logs .

for resolve this one we used the below code
log4j.appender.logAnalytics.logType=CUSTOM_LOG_NAME

still we getting like SparkLoggingEvent_CL 

we are not not understanding how to do this.

Could any one do help on this
Any help would be appreciated

Thankyou

**Comment by jocontr** [comment]
I would recommend the following documentation:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/custom-fields
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-sources-custom-logs
