### ISSUE TITLE
How to add additional custom field in log analaytics table using log4j

### ISSUE THREAD

**Issue by NarsingManda** [mspnp/spark-monitoring#79]
Actually we are using **log4j** to log the errors in **python**.
Everything is fine but we have requirement like add an custom fields to log analytics  table.

we are unable find out how to do this one using **log4j** in **python**

Could any one help on this

Any help is appreciated

**Comment by jocontr** [comment]
I would recommend the following documentation:
- https://docs.microsoft.com/en-us/azure/azure-monitor/platform/custom-fields
- https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-sources-custom-logs
