### ISSUE TITLE
Data for some attributes seem to be cut in Log Analytics Workspace

### ISSUE THREAD

**Issue by Innko** [mspnp/spark-monitoring#80]
I am trying to retrieve a report on the SQL queries that have been executed on a given cluster. What I noticed, however, when running querie agains the Log Analytics Workspace is that longer  SQL queries are cut and followed by "..." at the end. Attribute that houses this information is Properties_spark_job_description_s. 

Can you please help me understand how this can be modified to report the full query?

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [226371](https://dev.azure.com/ceapex/pnp/_workitems/edit/226371)

**Comment by jocontr** [comment]
Hi @Innko could you provide a sample query for my team to review? Thank you.

**Comment by Innko** [comment]
Hi, 
@jocontr sorry for late reply.  
<img width="700" alt="output" src="https://user-images.githubusercontent.com/44368077/84139543-c0fef600-aa58-11ea-988b-126f702ce775.PNG">

Hereby query:
SparkListenerEvent_CL
| where  Event_s  == "SparkListenerJobStart"
| join (
    SparkListenerEvent_CL
    | where Event_s == "SparkListenerJobEnd"
) on Job_ID_d, applicationId_s
| extend submission_time = unixtime_milliseconds_todatetime(Submission_Time_d), completion_time = unixtime_milliseconds_todatetime(Completion_Time_d1)
| extend jobDuration= completion_time - submission_time 
| project Job_ID_d, jobDuration , submission_time , completion_time, clusterName_s , Properties_user_s, applicationId_s, Properties_spark_databricks_clusterUsageTags_instanceWorkerEnvId_s, Properties_spark_job_description_s
| where submission_time > ago(24h) and notempty(Properties_user_s)

**Comment by hallihan** [comment]
It looks like this is dependent on how Spark is setting the job description for these jobs.  If you look in the cluster UI's Jobs or SQL displays, you will see that they show the same truncated value:
![image](https://user-images.githubusercontent.com/1796255/98981744-5f9df000-24ec-11eb-8d9b-9805e84e68c5.png)
Since this limitation comes from Spark and not from the spark-monitoring library, I'm closing this issue.
