### ISSUE TITLE
Support x-ms-AzureResourceId Header

### ISSUE THREAD

**Issue by juzuluag** [mspnp/spark-monitoring#84]
Current `LogAnalyticsClient.java` doesn't support setting `x-ms-AzureResourceId` request [header](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api#request-headers). This property would help to populate a unique identifier to track the az [resource](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-standard-properties#_resourceid) involved.

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [226373](https://dev.azure.com/ceapex/pnp/_workitems/edit/226373)

**Comment by juzuluag** [comment]
Hi @jocontr, great news. I do have some changes to propose, but not sure how is the process to contribute to the repo. Thanks for any insights.

**Comment by jocontr** [comment]
Hi @juzuluag it is very easy to contribute. If you have code; feel free to issue a pull request. If it is written guidance, you are also welcome to explore our various documents on the topic and as well propose a pull request against them. Here is a list of these: https://docs.microsoft.com/en-us/search/?search=databricks&scope=Azure%20Architecture%20Center

**Comment by juzuluag** [comment]
@jocontr , seems like I can't create a PR. I'm getting this error:
`git push --set-upstream origin juzuluag/add_x_ms_AzureResourceId
ERROR: Permission to mspnp/spark-monitoring.git denied to juzuluag.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
Any help, really appreciate.

**Comment by juzuluag** [comment]
Hi @jocontr , thank you for the invite. I have a PR out now. Any insights really appreciate.

**Comment by juzuluag** [comment]
Hi @jocontr , sorry to ping you again ;-), is there any process to get a code review in order to merge the proposed PR? Thanks for any help.
