### ISSUE TITLE
How to log only Error log from spark

### ISSUE THREAD

**Issue by guruvonline** [mspnp/spark-monitoring#91]
Hi,
I don't have any custom application logging done, but i want only "Error" logs from spark to be written to Log analytics. Is there any option to configure this? Presently it is logging everything Info/Warning/Error to Log analytics.

**Comment by hallihan** [comment]
You should be able to add a line with ```log4j.appender.logAnalyticsAppender.Threshold=ERROR``` at the end of the log4j config that the startup script generates: https://github.com/mspnp/spark-monitoring/blob/b8193707e849e661473f8cae71e60078f503e931/src/spark-listeners/scripts/spark-monitoring.sh#L87
