### ISSUE TITLE
spark continuously logging Error sending to Log Analytics

### ISSUE THREAD

**Issue by guruvonline** [mspnp/spark-monitoring#93]
HI,

I have added the monitoring package for my Structured Steaming job.(Azure Databricks runtime 6.4 spark 2.4.5, Scala 2.11). 
I can see the logs showing up in SparkLoggingEvent_CL and SparkListenerEvent_CL. But my spark job log in Databricks UI,
 continuously log error 

"Error sending to Log Analytics
java.io.IOException: Error sending to Log Analytics"
(attached image)
![LogAnalyticError](https://user-images.githubusercontent.com/46330056/85807305-5ca18f00-b706-11ea-9cdf-3477f7e2de0a.png)

Since i am using LogAnalytics to create any alert ,based on log query having any Error records. But I am not sure if some of the logs are not getting pushed to log analytics and my alert will not fire up if there are any error records which get dropped due to above error.

Thanks

**Comment by tarNeFyS** [comment]
I'm facing the same issue.

So far what i have on this : 
 - Only happens on clusters with AutoScaling turned on.
 - The error is generated by a  forbiden (403) answer to an http call to Azure Log Analytics

**Comment by guruvonline** [comment]
at least in my case cluster is not configured for AutoScale

**Comment by lorrinferdinand** [comment]
I'm facing the same issue.  MS says it is a known issue now for over 1 year.  This needs to be fixed we are scrambling to implement the mitigation which is to remove log analytics from the cluster!.

Please fix this bug!

**Comment by hurtn** [comment]
Facing the same error
Error sending to Log Analytics

**Comment by hurtn** [comment]
> Facing the same error having built the jars for 245 running on DBR 6.5. init script all set up and tried with both the sample jar and running in a notebook. Would be great if someone could give some options to diagnose or whether it is an issue with this Spark ver.
> java.io.IOException: Error sending to Log Analytics
> Error sending to Log Analytics

Apologies, managed solve this. The issue was to do with an incorrect setting spark-monitoring.sh file which referenced workspace ID incorrectly.

**Comment by hallihan** [comment]
This error is most often seen if the workspace id or key for the Log Analytics Workspace is not correct. Can anyone that has hit this confirm that they have added the correct values in https://github.com/mspnp/spark-monitoring/blob/b8193707e849e661473f8cae71e60078f503e931/src/spark-listeners/scripts/spark-monitoring.sh#L21-L22 before uploading the script to dbfs, and that they did not include any quote characters around the values?

**Comment by hallihan** [comment]
I haven't seen any additional data so I'm closing this issue.  If you are hitting this and can confirm that the spark-monitoring.sh script has correct values for the Log Analytics Workspace, please open a new issue.
