### ISSUE TITLE
Difference between logging through this API and spark logs configured at cluster level

### ISSUE THREAD

**Issue by sidtandon2014** [mspnp/spark-monitoring#94]
Hi,

I want to understand the difference between this APIs and cluster logs configured to send data to storage account.

**Comment by hallihan** [comment]
The logging provided by this implementation is more detailed, especially around the execution and metrics gathered for the individual job tasks.  See the following topic for specific scenarios:
<https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/>

The specific scenarios, and example logging events, for the preview diagnostic logging feature can be found at:
<https://docs.microsoft.com/en-us/azure/databricks/administration-guide/account-settings/azure-diagnostic-logs>
