### ISSUE TITLE
Only forward limited log to Azure Log Analytics

### ISSUE THREAD

**Issue by Wenhui-NL** [mspnp/spark-monitoring#95]
I built the library and tried it out in our environment for a few days and the cluster ran only a few hours per day but I'm receiving huge amount of log in the Azure Log Analytics workspace. I assume it can be configured to forward only the chosen logs. Could anybody help me out?

**Comment by slyons** [comment]
If you modify the [log4j](https://github.com/mspnp/spark-monitoring/blob/master/sample/spark-sample-job/src/main/resources/com/microsoft/pnp/samplejob/log4j.properties) properties file using the standard Log4J [properties syntax](https://logging.apache.org/log4j/2.x/manual/configuration.html) you should be able to limit the logs.

**Comment by Wenhui-NL** [comment]
Yes. My concern is more on the metrics which seems to account for a big portion. By increasing the *.sink.loganalytics.period in the sh file, I was able to adjust the volume of metrics as a whole but it's still a lot. To what extent, can this  be configured without affecting the monitoring ability?

**Comment by hallihan** [comment]
I did some quick experiments with filtering the data, see info and samples in this branch: <https://github.com/mspnp/spark-monitoring/blob/experiment-filtering/FILTER.md>

**Comment by kungfusoftware** [comment]
https://github.com/mspnp/spark-monitoring/blob/experiment-filtering/FILTER.md is not working. @hallihan , please fix the link

**Comment by hallihan** [comment]
@kungfusoftware this functionality was merged into main and can be found at: https://github.com/mspnp/spark-monitoring/blob/main/docs/filtering.md
