### ISSUE TITLE
Global Keyvault backed secrets

### ISSUE THREAD

**Issue by al-lac** [mspnp/spark-monitoring#96]
Is there a way to set global azure keyvault backed environment variables which can be used in init scripts?

Currently only setting them via the UI seems to work. 

I tried adding the following to **/databricks/spark/conf/spark-env.sh**, but that does not seem to work:

```
LOG_ANALYTICS_WORKSPACE_ID={{secrets/<secret-scope-name>/<keyvault-key-name>}}
LOG_ANALYTICS_WORKSPACE_KEY={{secrets/<secret-scope-name>/<keyvault-key-name>}}
```

Documentation:
https://github.com/mspnp/spark-monitoring/blob/master/docs/keyvault-backed-secrets.md

@Smarker Since you wrote the documentation, would you have any advice for me?

**Comment by marvinbuss** [comment]
@al-lac I guess you have used it with Databricks backed Secret Scopes?
Did that work for you?

I wanted to test Key Vault secret scopes as a next step, since a Databricks secret scope did work fine during my tests.

**Comment by al-lac** [comment]
Hi @marvinbuss, i only tested it with Key vault secret scopes. 

My problem is that i cannot set global environment variables and i do not want to configure it via the UI for every new cluster.

**Comment by marvinbuss** [comment]
@al-lac You can enforce them via cluster policies. Would that work for you? 

```json
{
    "spark_env_vars.LOG_ANALYTICS_WORKSPACE_ID": {
        "type": "fixed",
        "value": "{{secrets/mySecretScope/logAnalyticsWorkspaceId}}",
        "hidden": false
    }
}
```

**Comment by al-lac** [comment]
@marvinbuss In some way yes, but all already existing clusters would need to be switched to this policy which results in the deletion of other variables. 

I guess i will just set the variables once we create clusters with the databricks terraform provider.

**Comment by hallihan** [comment]
It looks like this is a design limitation for how Secret Scopes are managed in Databricks.  Closing this out as external to the spark-monitoring repo.  If you have developed useful alternatives for configuring the secrets, please feel free to submit as a PR to the documentation in this repo.
