### ISSUE TITLE
Cannot copy JAR files when Cluster running with a custom Docker image

### ISSUE THREAD

**Issue by locuba** [mspnp/spark-monitoring#98]
Hello,

I am working with Databricks and am looking to set up monitoring by collecting metrics into Azure Log Analytics, that's exactly what you are suggesting. After some issues I've finally managed to set it up on my DEV databricks using a basic cluster & default run time, no issue it's collecting the metrics however when trying with a more complex cluster using a custom docker image the init script is failing at the very begining.

**Here is my cluster:**
![image](https://user-images.githubusercontent.com/69255516/89434369-c2405c80-d743-11ea-930c-86e597bffe95.png)

The Init Script configuration:
![image](https://user-images.githubusercontent.com/69255516/89434472-de43fe00-d743-11ea-9010-89d02c0b1969.png)

After starting and finally stopped in error that's the error found in the cluster-logs:

> cp: cannot create regular file '/mnt/driver-daemon/jars': No such file or directory

It's happening in dbfs:/databricks/spark-monitoring/spark-monitoring.sh at line 63 when trying to copy the JAR files to the cluster: 

> cp -f "$STAGE_DIR/$JAR_FILENAME" /mnt/driver-daemon/jars

It seems this folder do not exist in the docker image I'm using, is there a way to bypass this? Is there a way to use another folder? If yes what other files shall I update to ensure this new folder will be used to use the JAR?

Thank you for your help

**Comment by slyons** [comment]
That step is just to get the JAR into the Classpath. What is the Docker image you're basing your custom one off of?

**Comment by locuba** [comment]
Finally after modifying the spark-monitoring.sh to copy all JAR to _/databricks/hive_ instead of _/mnt/driver-daemon/jars_ the init script ran without error this time and cluster is starting. However nothing is coming to Azure Log Analytics and I found this error in the log4j logs:

`log4j:ERROR Could not instantiate appender named "logAnalyticsAppender".`

So I guess the docker image the cluster does not find the expected Class (even if installed in the right folder, potential references to previous location I've changed?)

**Comment by locuba** [comment]
Hello,

I finally found what was wrong in my configuration, so my cluster running a docker image could not find the class logAnalyticsAppender because the JAR files were not copied at the right location, I was copying them to /databricks/hive where the program was not looking.

After trying different locations finally when copying to **/databricks/jars** it's working, cluster is sending metrics to Log Analytics.

spark-monitoring.sh sample:
```
echo "Copying Spark Monitoring jars"
JAR_FILENAME="/src/target/spark-listeners_${SPARK_VERSION}_${SPARK_SCALA_VERSION}-${SPARK_LISTENERS_VERSION}.jar"
echo "Copying $JAR_FILENAME"
cp -f "$STAGE_DIR/$JAR_FILENAME" **/databricks/jars**
JAR_FILENAME="/src/target/spark-listeners-loganalytics_${SPARK_VERSION}_${SPARK_SCALA_VERSION}-${SPARK_LISTENERS_LOG_ANALYTICS_VERSION}.jar"
echo "Copying $JAR_FILENAME"
cp -f "$STAGE_DIR/$JAR_FILENAME" **/databricks/jars**
echo "Copied Spark Monitoring jars successfully"
```
