### ISSUE TITLE
Spark monitoring script compatibility issues with Data bricks run time version beyond 6.3

### ISSUE THREAD

**Issue by raknaik** [mspnp/spark-monitoring#99]
Hi,

We had added the spark monitoring init script within our workspace for interactive and automated clusters which was running with runtime version of 6.3 (includes Apache Spark 2.4.4, Scala 2.11). But we now have issues with this runtime version since, this cluster's runtime version is out of support. We tried to change the run time version of the cluster instance beyond 6.3 and upon adding the init scripts we could see that the cluster start up time is more than expected.

Seeking your help in identifying this issue.

Regards,

Rakesh.N

**Comment by timo-aho** [comment]
Is this related to 7.0 compatibility: https://github.com/mspnp/spark-monitoring/issues/92

**Comment by al-lac** [comment]
@timo-aho i do not think it is related to the 7.0 compatibility. On our side everything is working fine until version 7. @raknaik can you post the output of the script?

**Comment by hallihan** [comment]
@raknaik I'm closing this issue for now.  If you have rebuilt the jars with the proper profile for your cluster and are still experiencing problems you can reopen this issue and provide more details.
